### ISSUE TITLE
torchvision._is_tracing()使用

### ISSUE THREAD

**Issue by AIgiraffe** [basaltzhang/tensorrt-plugin-demo#2]
您好，我有个关于torchvision_is_tracing()的问题，为什么要在输出位置做一些处理使得输出是固定维度的

**Comment by basaltzhang** [comment]
> 您好，我有个关于torchvision_is_tracing()的问题，为什么要在输出位置做一些处理使得输出是固定维度的

我理解是用于预分配空间，加快运行速度。

**Comment by basaltzhang** [comment]
长时间无回复，有问题请再打开。
